"use client";

import { Lightbulb, Sparkles } from "lucide-react";

export interface Insight {
  /** Tone affects the bullet color. "info" is the default. */
  tone?: "info" | "warn" | "good";
  /** Headline — short, lead-with-the-action wording. */
  text: string;
  /** Provenance — `"llm"` rows render with a small ✦ badge. Defaults to heuristic. */
  source?: "heuristic" | "llm";
}

const DOT_FOR_TONE: Record<NonNullable<Insight["tone"]>, string> = {
  warn: "bg-amber-500",
  good: "bg-emerald-500",
  info: "bg-sky-500",
};

export function InsightsPanel({
  title = "What this means",
  insights,
}: {
  title?: string;
  insights: Insight[];
}) {
  if (insights.length === 0) return null;
  return (
    <section className="mt-4 rounded-lg border border-border bg-card p-4">
      <header className="mb-2 flex items-center gap-2 text-sm font-semibold">
        <Lightbulb className="h-4 w-4 text-amber-500" aria-hidden /> {title}
      </header>
      <ul className="space-y-1.5 text-sm leading-relaxed">
        {insights.map((i, idx) => {
          const dot = DOT_FOR_TONE[i.tone ?? "info"];
          const isLlm = i.source === "llm";
          return (
            <li key={idx} className="flex items-start gap-2">
              <span className={`mt-1.5 inline-block h-1.5 w-1.5 shrink-0 rounded-full ${dot}`} aria-hidden />
              <span>
                {isLlm && (
                  <span
                    className="mr-1.5 inline-flex items-center gap-0.5 rounded-sm bg-primary/10 px-1 py-0.5 align-middle text-[9px] font-semibold uppercase tracking-wide text-primary"
                    title="Generated by Claude based on your panel data"
                  >
                    <Sparkles className="h-2.5 w-2.5" aria-hidden /> AI
                  </span>
                )}
                {i.text}
              </span>
            </li>
          );
        })}
      </ul>
    </section>
  );
}
