"use client";

import { useEffect, useState } from "react";
import { Sparkles } from "lucide-react";
import {
  fetchSkuNarrative,
  type HeuristicInsightInput,
} from "@/lib/api-client";
import type { SkuNarrative } from "@/lib/types";

interface Props {
  datasetId: string;
  skuId: string;
  sku: Record<string, unknown>;
  heuristics: HeuristicInsightInput[];
}

const TONE_DOT: Record<string, string> = {
  warn: "bg-amber-500",
  good: "bg-emerald-500",
  info: "bg-sky-500",
};

export function SkuNarrativeCard({ datasetId, skuId, sku, heuristics }: Props) {
  const [narrative, setNarrative] = useState<SkuNarrative | null>(null);
  const [loading, setLoading] = useState(true);
  const skuKey = JSON.stringify(sku);

  useEffect(() => {
    const ctrl = new AbortController();
    setLoading(true);
    fetchSkuNarrative(datasetId, skuId, sku, heuristics, ctrl.signal)
      .then((r) => setNarrative(r.narrative))
      .catch(() => setNarrative(null))
      .finally(() => setLoading(false));
    return () => ctrl.abort();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [datasetId, skuId, skuKey]);

  // Hide entirely while loading or if no narrative came back (no API key, etc.)
  if (loading || !narrative || (!narrative.paragraph && narrative.bullets.length === 0)) {
    return null;
  }

  return (
    <section className="rounded-lg border bg-card p-5">
      <header className="mb-2 flex items-center gap-2 text-sm font-semibold">
        <Sparkles className="h-4 w-4 text-primary" aria-hidden />
        Recommended actions
        <span
          className="rounded-sm bg-primary/10 px-1 py-0.5 text-[9px] font-semibold uppercase tracking-wide text-primary"
          title="Generated by Claude based on this SKU's forecast and policy"
        >
          AI
        </span>
      </header>
      {narrative.paragraph && (
        <p className="mb-3 text-sm leading-relaxed text-foreground/90">{narrative.paragraph}</p>
      )}
      {narrative.bullets.length > 0 && (
        <ul className="space-y-1.5 text-sm">
          {narrative.bullets.map((b, idx) => (
            <li key={idx} className="flex items-start gap-2">
              <span
                className={`mt-1.5 inline-block h-1.5 w-1.5 shrink-0 rounded-full ${TONE_DOT[b.tone] ?? "bg-sky-500"}`}
                aria-hidden
              />
              <span>{b.text}</span>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}
